parameters:
#    web_service_service.example.class: WebService\ServiceBundle\Example

services:
#    web_service_service.example:
#        class: %web_service_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
